import asyncio
import re
from playwright.async_api import Playwright, async_playwright, expect


async def run(playwright: Playwright) -> None:
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context()
    page = await context.new_page()
    await page.goto("https://test-m.jiangjunzh.com/pages/home/index")
    await page.get_by_label("租号").click()
    await page.get_by_label("出租账号，将军护航安全交易").click()
    await page.locator("uni-button").filter(has_text="密码登录").click()
    await page.get_by_role("spinbutton").click()
    await page.get_by_role("spinbutton").fill("19318589623")
    await page.get_by_role("textbox").click()
    await page.get_by_role("textbox").fill("123456")
    await page.get_by_label("同意服务协议").click()
    await page.locator("uni-button").filter(has_text=re.compile(r"^登录$")).click()
    await page.get_by_label("出租账号，将军护航安全交易").click()
    await page.get_by_text("我已悉知").click()
    await page.locator("uni-text").filter(has_text="请选择登录方式").click()
    await page.get_by_text("QQ登录").click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择账号登录方式").click()
    await page.get_by_text("扫码", exact=True).click()
    await page.get_by_text("确认").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^最早$")).click()
    await page.locator("uni-text").filter(has_text="确定").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^最晚$")).click()
    await page.get_by_text("确定").click()
    await page.locator("uni-text").filter(has_text="请选择人脸是否本人").click()
    await page.get_by_text("是", exact=True).click()
    await page.get_by_text("确认").click()
    await page.locator("uni-text").filter(has_text="请选择地区").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^福建省$")).click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^三明市$")).click()
    await page.locator("uni-input").filter(has_text="请填写哈夫币").get_by_role("textbox").click()
    await page.locator("uni-input").filter(has_text="请填写哈夫币").get_by_role("textbox").fill("26")
    await page.locator("uni-input").filter(has_text="请填写绝密KD").get_by_role("textbox").click()
    await page.locator("uni-input").filter(has_text="请填写绝密KD").get_by_role("textbox").fill("5")
    await page.locator("uni-input").filter(has_text="请填写账号等级").get_by_role("textbox").click()
    await page.locator("uni-input").filter(has_text="请填写账号等级").get_by_role("textbox").fill("60")
    await page.locator("uni-view").filter(has_text=re.compile(r"^请选择账号段位$")).click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^铂金$")).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择安全箱等级").click()
    await page.get_by_text("6格安全箱").click()
    await page.get_by_text("确认").click()
    await page.locator("uni-view:nth-child(14) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").click()
    await page.locator("uni-view:nth-child(14) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").fill("5")
    await page.get_by_text("请选择续费六格").click()
    await page.get_by_text("是").nth(5).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择体力等级").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^5级$")).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择负重等级").click()
    await page.get_by_text("6级", exact=True).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择特殊刀皮").click()
    await page.get_by_text("北极星").click()
    await page.get_by_text("龙牙").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^信条$")).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("点击上传支持jpg、png、webp，传得越多AI越准确").first.click()
    await page.locator("input[type=\"file\"]").set_input_files("20260722-100920.jpg")
    await page.get_by_text("点击上传支持jpg、png、webp，传得越多AI越准确").click()
    await page.locator("input[type=\"file\"]").set_input_files("邀请码.png")
    await page.locator(".uni-switch-input").first.click()
    await page.locator("uni-view:nth-child(2) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").first.click()
    await page.locator("uni-view:nth-child(2) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").first.fill("59")
    await page.locator("uni-view:nth-child(5) > uni-view:nth-child(2) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").click()
    await page.locator("uni-view:nth-child(5) > uni-view:nth-child(2) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").fill("2")
    await page.locator(".shrink-0 > .uni-switch-wrapper > .uni-switch-input").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^￥500测试——极端出租优惠劵$")).first.click()
    await page.locator("uni-view").filter(has_text="不使用优惠券").nth(3).click()
    await page.get_by_text("确定使用").click()
    await page.locator(".mb-_lfl_20rpx_lfr_ > .h-_lfl_24rpx_lfr_ > img").click()
    await page.locator("uni-button").filter(has_text="立即发布").click()
    await page.locator("uni-button").filter(has_text="立即支付").click()
    await page.close()

    # ---------------------
    await context.close()
    await browser.close()


async def main() -> None:
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())
