import asyncio
import re
from playwright.async_api import Playwright, async_playwright, expect


async def run(playwright: Playwright) -> None:
    browser = await playwright.chromium.launch(headless=False)
    context = await browser.new_context()
    page = await context.new_page()
    await page.goto("https://test-m.jiangjunzh.com/pages/home/index")
    await page.get_by_label("交易").click()
    await page.get_by_label("安全交易，随时随地尽在掌握，官方认证担保，海量账号，极速上号").get_by_role("img").click()
    await expect(page.get_by_label("安全交易，随时随地尽在掌握，官方认证担保，海量账号，极速上号").get_by_role("img")).to_be_visible()
    await page.get_by_label("安全交易，随时随地尽在掌握，官方认证担保，海量账号，极速上号").get_by_role("img").click()
    await page.wait_for_timeout(2000)
    await page.locator(".grid.grid-cols-2 > uni-button:nth-child(2)").click(force=True)
    await page.wait_for_timeout(3000)
    
    # 尝试多种方式查找密码登录按钮
    password_login_found = False
    password_login_selectors = [
        page.locator("uni-button").filter(has_text="密码登录"),
        page.get_by_text("密码登录"),
        page.locator("[class*=\"password\"]")
    ]
    
    for selector in password_login_selectors:
        try:
            await selector.wait_for(state="visible", timeout=10000)
            await selector.click()
            password_login_found = True
            break
        except:
            continue
    
    if not password_login_found:
        # 如果找不到密码登录按钮，说明可能已经在密码登录页面或者页面结构不同
        print("未找到密码登录按钮，继续执行")
    await page.get_by_role("spinbutton").click()
    await page.get_by_role("spin button").fill("19318589623")
    await page.get_by_role("textbox").click()
    await page.get_by_role("textbox").fill("123456")
    await page.get_by_label("同意服务协议").click()
    await page.locator("uni-button").filter(has_text=re.compile(r"^登录$")).click()
    await page.locator(".grid.grid-cols-2 > uni-button:nth-child(2)").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^QQ登录$")).click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^自主发布$")).click()
    await page.get_by_role("img").nth(2).click()
    await page.locator("input[type=\"file\"]").set_input_files("20260722-100920.jpg")
    await page.locator(".h-_lfl_96rpx_lfr_ > img").first.click()
    await page.locator("input[type=\"file\"]").set_input_files("20260722-100920.jpg")
    await page.locator("input[type=\"text\"]").click()
    await page.locator("input[type=\"text\"]").fill("325454")
    await page.get_by_text("请选择二次实名").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^可二次实名$")).click()
    await page.get_by_text("确认").click()
    await page.locator(".h-_lfl_96rpx_lfr_ > img").click()
    await page.locator("input[type=\"file\"]").nth(1).set_input_files("屏幕录制 2026-07-21 174938.mp4")
    await page.locator("uni-input").filter(has_text="请填写总资产").get_by_role("spinbutton").click()
    await page.locator("uni-input").filter(has_text="请填写总资产").get_by_role("spinbutton").fill("25")
    await page.locator("uni-input").filter(has_text="请填写哈夫币纯币").get_by_role("spinbutton").click()
    await page.locator("uni-input").filter(has_text="请填写哈夫币纯币").get_by_role("spinbutton").fill("12")
    await page.get_by_text("请选择安全箱", exact=True).click()
    await page.get_by_text("顶级安全箱(3*3)").click()
    await page.locator("uni-view").filter(has_text="顶级安全箱(3*3)高级安全箱(2*3)进阶安全箱(2*2").nth(3).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择安全箱皮肤").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^S6：蚀金华彩$")).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择刀皮").click()
    await page.get_by_text("坠星者").click()
    await page.get_by_text("电锯惊魂").click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择挂饰-传说典藏").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^统统拿走$")).click()
    await page.get_by_text("肘击王").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^骇客纪元$")).click()
    await page.get_by_text("非洲之心").click()
    await page.get_by_text("命运之轮").click()
    await page.get_by_text("财神到").click()
    await page.get_by_text("黑夜猎手").click()
    await page.get_by_text("余烬之影").click()
    await page.get_by_text("命运之轮财神到黑夜猎手统统拿走肘击王余烬之影幸运鼠鼠骇客纪元黑暗摇滚毁灭之源非洲之心").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^统统拿走$")).click()
    await page.get_by_text("毁灭之源").click()
    await page.get_by_text("黑暗摇滚").click()
    await page.get_by_text("幸运鼠鼠").click()
    await page.get_by_text("统统拿走").click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择武器-传说典藏").click()
    await page.get_by_text("SCAR-电玩高手").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^M250-电玩高手$")).click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^QBZ95-王牌之剑$")).click()
    await page.get_by_text("AS Val-悬赏令").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^腾龙-气象感应$")).click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^AUG-气象感应$")).click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^MP7-电玩高手$")).click()
    await page.get_by_text("Vctor-美杜莎").click()
    await page.get_by_text("KC17-造物纪元").click()
    await page.get_by_text("M7-棱镜攻势S2").click()
    await page.get_by_text("M4A1-棱镜攻势").click()
    await page.get_by_text("K416-命运").click()
    await page.locator(".absolute > img").click()
    await page.get_by_text("请选择仓库").click()
    await page.get_by_text("仓库LV.10").click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择靶场").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^靶场LV\.7$")).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择训练中心").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^训练中心LV\.7$")).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择潜水中心").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^潜水中心LV\.3$")).click()
    await page.get_by_text("确认").click()
    await page.get_by_text("请选择收藏室").click()
    await page.get_by_text("收藏室LV.2").click()
    await page.get_by_text("确认").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^请选择干员外观$")).click()
    await page.locator("uni-text").filter(has_text="至臻/典藏红皮").click()
    await page.get_by_text("露娜 – 黑·天际线 ✓").click()
    await page.get_by_text("麦晓雯（骇爪）– 水墨云图").click()
    await page.get_by_text("红狼-蚀金玫瑰 ✓").click()
    await page.get_by_text("威龙 – 凌霄戍卫 ✓").click()
    await page.get_by_text("麦晓雯 – 维什戴尔（明日方舟联动） ✓").click()
    await page.get_by_text("蛊-能天使·午夜邮差 ✓").click()
    await page.get_by_text("全部").click()
    await page.locator("uni-text").filter(has_text="传说金皮").click()
    await page.get_by_text("威龙 – 铁面判官（S1）").click()
    await page.get_by_text("威龙 – 蛟龙特战队").click()
    await page.get_by_text("蜂医 – 危险物质").click()
    await page.get_by_text("蜂医 – 送葬人·无题密令").click()
    await page.get_by_text("无名-夜鹰 ✓").click()
    await page.get_by_text("深蓝 – 不破誓约（S6）").click()
    await page.get_by_text("红狼 – 电锯惊魂").click()
    await page.get_by_text("露娜 – 金牌射手（S7） ✓").click()
    await page.get_by_text("乌鲁鲁 – 荒原猎手（S8） ✓").click()
    await page.get_by_text("威龙 – 壮志凌云（S3）").click()
    await page.get_by_text("全部").click()
    await page.get_by_text("确定(16)").click()
    await page.locator("uni-input").filter(has_text="请填写烽火地带等级（1-60）").get_by_role("spinbutton").click()
    await page.locator("uni-input").filter(has_text="请填写烽火地带等级（1-60）").get_by_role("spinbutton").fill("55")
    await page.get_by_text("请选择烽火地带段位").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^铂金$")).click()
    await page.locator("uni-view").filter(has_text="青铜白银黄金铂金钻石黑鹰巅峰").nth(3).click()
    await page.get_by_text("确认").click()
    await page.locator("uni-input").filter(has_text="请填写全面战场等级（1-60）").get_by_role("spinbutton").click()
    await page.locator("uni-input").filter(has_text="请填写全面战场等级（1-60）").get_by_role("spinbutton").fill("55")
    await page.get_by_text("请选择全面战场段位").click()
    await page.get_by_text("尉官").click()
    await page.get_by_text("确认").click()
    await page.locator("uni-view:nth-child(19) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").click()
    await page.locator("uni-view:nth-child(19) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").fill("5")
    await page.locator("uni-text").filter(has_text="请选择通行证").click()
    await page.locator("uni-view").filter(has_text=re.compile(r"^S7$")).click()
    await page.get_by_text("确认").click()
    await page.locator("uni-view:nth-child(21) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").click()
    await page.locator("uni-view:nth-child(21) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").fill("55")
    await page.locator("uni-view:nth-child(22) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").click()
    await page.locator("uni-view:nth-child(22) > .relative > .font-body > .uni-input-wrapper > .uni-input-input").fill("55")
    await page.locator(".font-body > .mb-_lfl_36rpx_lfr_ > .rounded-_lfl_20rpx_lfr_ > uni-view > .relative > .font-body > .uni-input-wrapper > .uni-input-input").click()
    await page.locator(".font-body > .mb-_lfl_36rpx_lfr_ > .rounded-_lfl_20rpx_lfr_ > uni-view > .relative > .font-body > .uni-input-wrapper > .uni-input-input").fill("55")
    await page.locator(".uni-switch-input").click()
    await page.locator(".h-_lfl_24rpx_lfr_ > img").click()
    await page.locator("uni-button").filter(has_text="立即发布").click()
    await page.close()

    # ---------------------
    await context.close()
    await browser.close()


async def main() -> None:
    async with async_playwright() as playwright:
        await run(playwright)


asyncio.run(main())